gui:
  mouseEvents: true
  commitLength:
    show: true
  sidePanelWidth: 0.3333

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: "W"
    context: "global"
    command: "git commit --no-verify"
    subprocess: true
  - key: "B"
    command: 'gh browse "{{.SelectedPath}}"'
    context: "files"
  - key: "B"
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
