#
# Options
#

set -g mouse on
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g monitor-activity on
# Picker bindings for tmux_session_manager.
set -g @tsm_picker_slot_1_key "ctrl-u"
set -g @tsm_picker_slot_2_key "ctrl-i"
set -g @tsm_picker_slot_3_key "ctrl-o"
set -g @tsm_picker_slot_4_key "ctrl-p"
# Remember 50,000 lines.
set-option -g history-limit 50000

#
# Keybindings
#

# Toggle the status bar with <prefix>b
bind-key b set-option status

# Use Shift+Enter to send C-j which acts as a newline in most terminals.
bind-key -T root S-Enter send-keys C-j

#
# Style Status bar
#

set-option -g status-position top
set-option -g status-left '#[bold]#[bg=green,fg=black] #S#[bg=black,fg=green]'
set-option -g status-left-length 50
set-option -g status-right '#(~/.config/tmux/get_status_right.sh)'
set-option -g status-right-length 200
set-option -g status-bg black
set-option -g status-fg blue
set -g window-status-current-format ''
set -g window-status-format ''
set-hook -g client-session-changed 'refresh-client -S'

#
# Plugins
#

# Initialize local plugins
run '~/.config/tmux/local_plugins/tmux_session_manager/plugin.tmux'

# Session manager bindings.
bind-key u run-shell '~/.config/tmux/local_plugins/tmux_session_manager/tsm slot-1'
bind-key i run-shell '~/.config/tmux/local_plugins/tmux_session_manager/tsm slot-2'
bind-key o run-shell '~/.config/tmux/local_plugins/tmux_session_manager/tsm slot-3'
bind-key p run-shell '~/.config/tmux/local_plugins/tmux_session_manager/tsm slot-4'
bind-key s run-shell '~/.config/tmux/local_plugins/tmux_session_manager/tsm open'
bind-key S run-shell '~/.config/tmux/local_plugins/tmux_session_manager/tsm pick-dir ~/Documents/coding/'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
